/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountingTeamRouteImport } from './routes/accounting-team'
import { Route as AuditTeamRouteImport } from './routes/audit-team'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as WhyCalverisRouteImport } from './routes/why-calveris'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingTeamRoute = AccountingTeamRouteImport.update({
  id: '/accounting-team',
  path: '/accounting-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTeamRoute = AuditTeamRouteImport.update({
  id: '/audit-team',
  path: '/audit-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyCalverisRoute = WhyCalverisRouteImport.update({
  id: '/why-calveris',
  path: '/why-calveris',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting-team': typeof AccountingTeamRoute
  '/audit-team': typeof AuditTeamRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/why-calveris': typeof WhyCalverisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting-team': typeof AccountingTeamRoute
  '/audit-team': typeof AuditTeamRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/why-calveris': typeof WhyCalverisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting-team': typeof AccountingTeamRoute
  '/audit-team': typeof AuditTeamRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/why-calveris': typeof WhyCalverisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounting-team'
    | '/audit-team'
    | '/contact'
    | '/how-it-works'
    | '/why-calveris'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounting-team'
    | '/audit-team'
    | '/contact'
    | '/how-it-works'
    | '/why-calveris'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounting-team'
    | '/audit-team'
    | '/contact'
    | '/how-it-works'
    | '/why-calveris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountingTeamRoute: typeof AccountingTeamRoute
  AuditTeamRoute: typeof AuditTeamRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  WhyCalverisRoute: typeof WhyCalverisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-team': {
      id: '/accounting-team'
      path: '/accounting-team'
      fullPath: '/accounting-team'
      preLoaderRoute: typeof AccountingTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-team': {
      id: '/audit-team'
      path: '/audit-team'
      fullPath: '/audit-team'
      preLoaderRoute: typeof AuditTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-calveris': {
      id: '/why-calveris'
      path: '/why-calveris'
      fullPath: '/why-calveris'
      preLoaderRoute: typeof WhyCalverisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountingTeamRoute: AccountingTeamRoute,
  AuditTeamRoute: AuditTeamRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  WhyCalverisRoute: WhyCalverisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
